# Generated by Django 5.0.2 on 2024-02-21 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_app', '0002_products_category_alter_products_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi_app.category'),
        ),
    ]
